apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-lp-deployment
  namespace: staging
  labels:
    app: staging-lp
    env: staging
spec:
  selector:
    matchLabels:
      app: staging-lp
      env: staging
  replicas: 2
  template:
    metadata:
      labels:
        app: staging-lp
        env: staging
    spec:
      containers:
      - name: staging-lp
        image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s-lp-service
  namespace: staging
  labels:
    app: staging-lp
    env: staging
spec:
  type: NodePort
  selector:
    app: staging-lp
  ports:
    - port: 80
      protocol: TCP

---